# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sensor_data_viewer
                                 A QGIS plugin
 This plugin displays sensor data from the 5gLa project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-03
        copyright            : (C) 2024 by Lukas Lange - Blue Sky Operations GmbH
        email                : ll@vitrum-connect.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load sensor_data_viewer class from file sensor_data_viewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sensor Data Viewer import sensor_data_viewer
    return sensor_data_viewer(iface)
