# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SensorDataViewer
                                 A QGIS plugin
 Viewing sensor data from the 5gLa platform
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-11
        copyright            : (C) 2024 by Blue Sky Operations GmbH
        email                : ll@blue-sky-ops.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SensorDataViewer class from file SensorDataViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sensor_data_viewer import SensorDataViewer
    return SensorDataViewer(iface)
