# -*- coding: utf-8 -*-
"""
/***************************************************************************
 fivegla_visualization
                                 A QGIS plugin
 This plugin visualizes the measured values ​​and results of the 5GLa project.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-29
        copyright            : (C) 2024 by Lukas Lange / Blue Sky Operations GmbH
        email                : ll@blue-sky-ops.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load fivegla_visualization class from file fivegla_visualization.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .fivegla_visualization import fivegla_visualization
    return fivegla_visualization(iface)
